### ISSUE TITLE
Backwards Shooting

### ISSUE THREAD

**Issue by smithxn** [mopioid/Borderlands-Commander#1]
Hello Mopioid! thanks for making this amazing mod since i always wanted to play BL2 in thirdperson, but i ran into a problem, at first it was working fine, but when i got to Liars Berg while i was firing, it seemed the pistol wasn't shooting any bullets, this also happened to other guns when i swapped to them about 3 seconds after swapping to them. I only noticed it shooting backwards when i shot a torgue shotgun with slow enough projectiles to see where it was going. I am unsure of how to really mod things myself, I also don't know if this is an issue that can be avoided, but something i **did** notice was that the pistol seems to have like a second set of crosshairs on it's right just i tiny bit to the right of the crosshairs, idk if his has something to do with it or indicates  anything, i just thought it might be relevant. Sorry if i'm just wasting time and this is something i should've known, is an unfixable problem, or i'm just stupid, but i just wanted to let it be known. Once again thanks so much for making an amazing mod like this and i hope you can get back to me. ^_^

**Comment by mopioid** [comment]
Yup, this is a known flaw with the game's hidden third person camera "setting." Perhaps it is possible to devise a mod to fix it, but that is beyond the scope of Commander. Sorry!

**Comment by smithxn** [comment]
Thanks was just wondering whether or not it was fixable or just a problem with the game, thanks for the response! ^_^
