### ISSUE TITLE
Cant download borderlands-commander.zip

### ISSUE THREAD

**Issue by SunmanXD** [mopioid/Borderlands-Commander#10]
says it contains a virus and will not allow me to download, have disabled all anti virus/firmware/malware software and tried multiple browsers with no success

**Comment by SammichBro** [comment]
Same problem here, really want to try it out. Looks great Mopi and Co.

**Comment by RiverParkourist** [comment]
I just recently got this as well, which is weird because the first time i downloaded it windows didnt pick up anything. The mod works great for me aside from the few times it doesnt boot up correctly. But hopefully we should be safe.

**Comment by bruahara** [comment]
yeah, still having the same problem.
