### ISSUE TITLE
Crashes when I try to use it

### ISSUE THREAD

**Issue by CritikalErorr** [mopioid/Borderlands-Commander#14]
I went back and followed the steps for a second time just to see if I missed anything, and I am 100% certain I did not. However, when NOT in-game I can use the hotkeys and windows beeps at me. This I've found to be normal, but once you get in-game. If you try using the program. It just crashes for seemingly no reason. I checked the command injector, and it says it booted up just fine, as for the program it's self. It doesn't have a log I can view. 

EDIT: After I posted this, I went in-game to see if the numpad hotkeys also crash it, and they do. I also tried uninstalling AutoHotkey a program I use to make my own hotkeys, and it did nothing it still crashed. Also, running bl commander as admin didn't help. Still crashing when inputs are made.

**Comment by avocaado** [comment]
Same from me, was really hoping to start testing this amazing feature but it crashes everytime i try to use it.

**Comment by c0dycode** [comment]
Could you both tell me what your Windowslanguage is?

Is it RU by any chance?

**Comment by CritikalErorr** [comment]
English US

**Comment by CritikalErorr** [comment]
I deleted the last comment, I had fixed that issue. I had the tps command injector in that folder before. So that's fixed.

**Comment by CritikalErorr** [comment]
omg I suck that this

**Comment by c0dycode** [comment]
Okay, glad you got it fixed @CritikalErorr.

For you @avocaado and @jim343, please check out the solution provided above. If that doesn't solve the issue for either of you, please open up a seperate issue on here.

**Comment by CritikalErorr** [comment]
No no no, that for the game not opening when bl commander was running. Bl commander still crashes

**Comment by c0dycode** [comment]
Ahhh, okay. In that case, try this version. It's actually supposed to fix an issue on RU-systems and is basically #11 but that version is not uploaded yet.

Just for the chance of it fixing it for you guys aswell, check the attached version. 
[Borderlands Commander.zip](https://github.com/mopioid/Borderlands-Commander/files/2719082/Borderlands.Commander.zip)

**Comment by jim343** [comment]
I just don’t understand how I have had it working before but instead of using hexeditor I’m using the Blcmm if that made the difference

**Comment by CritikalErorr** [comment]
So, using the RU fix. Seems to have fixed it. Which is odd, but thank you.
