### ISSUE TITLE
borderlands commander not responding to hotkeys or symbols  

### ISSUE THREAD

**Issue by jim343** [mopioid/Borderlands-Commander#15]
ive  followed the steps perfectly but it isn't working at all i recently restored my computer but before i did that i had it working fine and now all of a sudden its not working only difference is the other game was hex edited and this one is not because im using the blcmm

**Comment by jasmine2785** [comment]
Same goes for me, using BLCMM 1.1.8 on steam with windows 10.  Dont know whats going on, i did unable hex edit in BLCMM.
