### ISSUE TITLE
.Exe disappeared

### ISSUE THREAD

**Issue by Elsinore28** [mopioid/Borderlands-Commander#16]
I have been happily using the Commander for months now and today the exe disappeared. I have since tried to re-download it and the .exe file isnt there. I have disabled all anti-virus software, even though it didnt effect it before

**Comment by gctypo** [comment]
Windows Defender thinks Commander is a virus, since it injects code into another application. If you disable all third-party antivirus software, Windows Defender will step in as the default. You'll have to look at the scan history and un-quarantine the program.
