### ISSUE TITLE
Borderlands The Presequel crash bevor starting

### ISSUE THREAD

**Issue by ciansatlas** [mopioid/Borderlands-Commander#17]
So i have the problem when i start Borderlands TPS with borderlands commands it starts normally but if i see the first loading screen on my desktop it dissapears and nothing happen, i tryd it 5 times with all the files and it happens again and again, maybe u can help me 

Sorry for the bad englisch

**Comment by AvoidAtAllCosts** [comment]
I have the same problem, but it seems to go away when I remove/rename the "ddraw.dll" file in the Win32 folder. This does however break any plugins you have (including Borderlands Commander)

**Comment by ciansatlas** [comment]
does it work when i rename it ?

**Comment by AvoidAtAllCosts** [comment]
The problem was fixed when c0dycode changed the Commanderinjector.dll or Autoexec.dll files 15 hours ago I believe, at least for me.

**Comment by ciansatlas** [comment]
ok thank u :)
