### ISSUE TITLE
Borderlands 2 crashing

### ISSUE THREAD

**Issue by PZPLCiastek** [mopioid/Borderlands-Commander#19]
Borderlands 2 is crashing on start up since new update. Could you please update BC to newest version of BL2?

**Comment by fntq** [comment]
yea after load launcher game crash, you gonna make new version?

**Comment by Vandasius** [comment]
Crashes for me too.

**Comment by Envyleva** [comment]
It is crashing on update but when you remove the ddraw.dl it fixes so this one might be on cody not mop. Also keep up the good work guys! :D

**Comment by BecksIsAlreadyTaken** [comment]
Not using UHD pack, the game still crashes

**Comment by the-pieman** [comment]
Bump, I'm having the same issue (Post UHD update)

**Comment by BecksIsAlreadyTaken** [comment]
You need to update the readme.md. i tried using uhd-version commander and it works

**Comment by Magic-Chef** [comment]
What steps did you take to make it work?

**Comment by the-pieman** [comment]
> 
> 
> What steps did you take to make it work?

You open the zip and use the file specifically labelled for UHD, not the one that just says BL2 or PS

**Comment by Magic-Chef** [comment]
oooooh, I did not realize he had released one for UHD, I was using the old one... Thank you!
