### ISSUE TITLE
Borderlands Commander exiting when launching bl2

### ISSUE THREAD

**Issue by Pingu67** [mopioid/Borderlands-Commander#2]
I have put all the correct files in the correct places but upon launch of bl2 I find nothing has changed I try button commands nothing I tab out and check the commander and after hovering over it the commander disappears. Need Help

**Comment by Brosepy** [comment]
same thing is happening to me. no binds work and then the program crashes.

**Comment by konmanyockey** [comment]
it may be the system your using. I'm using windows 10. and the instillation seems to show an older model
