### ISSUE TITLE
Borderlands 2 Commander Lilith and fight for Sanctuary crashing

### ISSUE THREAD

**Issue by EarlGray26** [mopioid/Borderlands-Commander#21]
After the last update of 06/10/19, when using Borderlands Commander, the game crashes, what should I do?

**Comment by overpaid** [comment]
Did you find a fix? Having the same problem.

**Comment by EarlGray26** [comment]
Yea, the fix is simple: you just need to download the latest version of CommandInjector from codycode's github. The problem lies in him
