### ISSUE TITLE
Can't download Borderlands-Commander.zip

### ISSUE THREAD

**Issue by jorgebohyn** [mopioid/Borderlands-Commander#25]
The Borderlands-Commander.zip file has a virus according to my pc and is preventing me from downloading it. Does anyone else have the same problem and know how to solve it?

**Comment by RobertVorback** [comment]
Are you still looking for help with this?
Are you using Windows 10? if so you may need to add an exclusion
to Windows Defender, I had the same problem and fixed it
by adding a file exclusion for the zip file

**Comment by jorgebohyn** [comment]
Thank you for responding and yes, I'm still looking for help.
So, where can I find that file exclusion that I need to add to Windows Defender?

**Comment by RobertVorback** [comment]
Sorry for my late reply, I was just abouy to suggest this web page:
[https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security](url)

But you have figured it out already
Cheers
