### ISSUE TITLE
Load save

### ISSUE THREAD

**Issue by lauramachts** [mopioid/Borderlands-Commander#27]
Is there a way to load a save after i quit the game? I can load the save states when i'm at the game but i don't find this very useful since the checkpoints do the same job. I wanted to run the game and then load the last save state i made so i don't have to pass the whole stage all over again to return where i stopped the last time.

**Comment by mopioid** [comment]
To request features for Borderlands Commander, visit the Discord server: https://discord.gg/54DE8uXvHE
