### ISSUE TITLE
Save and Restore Position won't work

### ISSUE THREAD

**Issue by JayyFKay** [mopioid/Borderlands-Commander#28]
Wanted to try this mod out, conveniently there was a new version now implemented in Python but sadly all the features work except for Save and Restore Position, the one i wanted to use :D tried redownloading it a couple of times and switching the key bind, nothing worked.

**Comment by arnold-the-duck** [comment]
Toggle Damage Numbers also fails for me. The problems are due to the variables _ModInstance and _DamageNumberEmitterObject being undefined. The fixes are simple and I'm sure mopioid will have it running properly soon.
