### ISSUE TITLE
There is a Trojan in the files of this download

### ISSUE THREAD

**Issue by Brosepy** [mopioid/Borderlands-Commander#3]
nice. when i try to download it it gets stopped as soon as it started saying that its a Trojan i half way believe but i dont want to because if it is true then joltzdude and all his people that downloaded this now have a Trojan.

**Comment by Brosepy** [comment]
![f4f9672f2130c2715efd157ecb50a4ba](https://user-images.githubusercontent.com/43187511/45393865-8eaa3580-b5f3-11e8-9f16-dbf0a5f67a71.png)

**Comment by Brosepy** [comment]
also if you do have a trojan can i just get the regular download without you taking control of my computer sir or madam

**Comment by Brosepy** [comment]
never mind got it lol

**Comment by Ki11Y0urs3lf** [comment]
> never mind got it lol

How did you get it? Cause i can't download too
