### ISSUE TITLE
Save quiting causes lag

### ISSUE THREAD

**Issue by OttoAhlfors** [mopioid/Borderlands-Commander#30]
The quick save and quit button seems to cause massive lag specifly in pause menu after it has been used a couple of times. Restarting the game fixes this but is pretty anoying to go every 20 or so minutes. There also seems to be a broblem that when this lag happens and I quit the game normaly it loads back in by itself. Making it so that the only way to shut the game is trough task manager.

**Comment by mopioid** [comment]
Can you confirm this issue still occurs, and that uninstalling Borderlands Commander fixes it?

**Comment by CtrlAltCuteness** [comment]
There was a command for saving, returning to the title screen, and reloading that save after the title screen finishes loading. I forgot which mod it was (and which version), but I recall it existing and doing that exact issue.

**Comment by mopioid** [comment]
Yeah my impression is that this is unrelated to Commander. Thanks!
