### ISSUE TITLE
Mod Not Showing Up In Mod Menu

### ISSUE THREAD

**Issue by Misterman99** [mopioid/Borderlands-Commander#31]
I have the commander folder from the main download folder in the my mods folder, but when I go in game the mod does not show up in my mod list. Not sure what I have done wrong or what is messed up, any help would be very appreciated!

**Comment by ghgto** [comment]
It`s a python file bruh

**Comment by Djouwi** [comment]
I have the same issues, i launch my game, open mods ( phython sdk ) and i can't find it.... I searched for an hour on the internet to understand why it does'nt show up and found nothing..
Can somebody help ?

**Comment by mopioid** [comment]
For general troubleshooting installing Borderlands Commander, visit the Discord server: https://discord.gg/54DE8uXvHE
