### ISSUE TITLE
Failing to import commander

### ISSUE THREAD

**Issue by Naxx00** [mopioid/Borderlands-Commander#32]
I had downloaded this mod and it didnt show up in my mods folder so i click f6 for console and there it is 
![image](https://user-images.githubusercontent.com/90341892/132547996-ae1fd38e-d714-4c20-8749-12740c195c1f.png)

I redownloaded many times and it does not work, i updated sdk and still this error exists.

**Comment by mopioid** [comment]
This is caused by the presence of another mod which predated modern versions of the SDK. Apologies, I cannot recall the name, but you should be able to track it down easily.
