### ISSUE TITLE
Teleport issue

### ISSUE THREAD

**Issue by AmaterkA** [mopioid/Borderlands-Commander#8]
So I don´t know what I do wrong.
BL Commander works great, I can use save/restore position, change speed, freeze game etc.
But I cannot use teleporting with "Control + Up / Down / Left / Right" because when I tried to press buttons, nothing happened and commander crashed. I tried perhaps everything - like rebind in-game keys, blcommander.exe run as administrator, switch numpad/symbol binding. I have latest updates.
"Control + End" works.

Thanks for help and I´m sorry for my English.

**Comment by c0dycode** [comment]
This should be fixed once there's a new build by mopi which uses #11
